[package]
name = "OneValleyGameFi"
edition = "2024.beta"
license = "MIT"
authors = ["OneValley Team"]

[dependencies]
One = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/one-framework", rev = "main" }

[addresses]
one_valley_gamefi = "0x0"